name = "     Code with Ranga"
name = name.strip()
print(name.strip())
print(len(name))
print(name.endswith("Ranga"))
print(name.startswith("Code"))
print(name.count("a"))
print(name.capitalize())
print(name.find("with"))
print(name.replace("Ranga","RangaSesha"))
print(name.upper())
print(name.lower())
print(name.casefold())
print(name)
print(name.strip())
print(name.split(' '))
